apiVersion: v1
kind: Secret
metadata:
  name: smartdine-secrets
  namespace: smartdine
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9tYXJhdGhlazMyMV9kYl91c2VyOktydXNobmEuMTIzQHNtYXJ0ZGluZS42NWMybHJ0Lm1vbmdvZGIubmV0L1BPUz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
  JWT_SECRET: bXlTdXBlclNlY3JldEtleQ==
